backend:
  name: git-gateway
  branch: master

media_folder: "static/img"
public_folder: "img"

collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "HomePage"
        name: "home"
        file: "content/_index.md"
        fields:
          - label: "Header"
            name: "header"
            widget: "object"
            fields:
              - label: "Brand"
                name: "brand"
                widget: "string"
              - label: "Navbar"
                name: "navbar"
                widget: "object"
                fields:
                  - label: "Home"
                    name: "home"
                    widget: "string"
                  - label: "Services"
                    name: "services"
                    widget: "string"
                  - label: "Explore"
                    name: "explore"
                    widget: "string"
                  - label: "Testimony"
                    name: "testimony"
                    widget: "string"
                  - label: "Pricing"
                    name: "pricing"
                    widget: "string"
                  - label: "Team"
                    name: "team"
                    widget: "string"
                  - label: "Blog"
                    name: "blog"
                    widget: "string"
                  - label: "Faq"
                    name: "faq"
                    widget: "string"
                  - label: "Singn-up"
                    name: "signup"
                    widget: "string"
                  - label: "Login"
                    name: "login"
                    widget: "string" 
          - label: "Banner"
            name: "banner"
            widget: "object"
            fields:
              - label: "h1"
                name: "h1"
                widget: "string"
            